### ISSUE TITLE
leaderboard not showing other people's rank

### ISSUE THREAD

**Issue by JeeheonKim** [avinash-vk/algobot#1]
![image](https://user-images.githubusercontent.com/39718076/105623580-d7d83a00-5de8-11eb-8ea5-2e7a38f1e0c0.png)

Hello developer! When I type `;leaderboard` it only shows my name :(

**Comment by nicksuh** [comment]
![leaderboard](https://user-images.githubusercontent.com/13486893/105637005-737fae00-5eae-11eb-800b-168df288c951.JPG)
currently ranking system is a bit weird

**Comment by avinash-vk** [comment]
Thanks for trying it out guys! Will fix these issues asap. @JeeheonKim @s646054

**Comment by avinash-vk** [comment]
Fixed this! Thanks again xD
